version: "3"

services:
  database: 
    image: neo4j:enterprise
    restart: always
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins

    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ABhijeet55
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_apoc_uuid_node_enabled=true
      - NEO4J_apoc_uuid_relationship_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_useneo4jconfig=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]

volumes:
  database:
