version: "3"

services:
  database: 
    image: neo4j:latest
    restart: always
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
#     environment:
#       - NEO4J_AUTH=neo4j/password
#       - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
#       - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
#       - NEO4J_dbms_security_procedures_allowlist=gds.*, apoc.*
#       - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*

volumes:
  database:
